### ISSUE TITLE
Memory leak on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [kornelski/lodepng-rust#28]
lodepng-rust leaks memory when given malicious input. This issue has been discovered via fuzzing with [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz).

Steps to reproduce:
```
git clone https://github.com/Shnatsel/lodepng-leak.git
cd lodepng-leak
RUSTFLAGS='--cfg fuzzing' cargo run
```
PNG and deflate checksums make fuzzing impossible, so I have modified lodepng-fuzz to disable checksum verification during fuzzing via conditional compilation. lodepng-leak repo currently links against my modified version, which can be found [here](https://github.com/Shnatsel/lodepng-rust) along with the fuzzing setup. The code right now is rather messy, but it would be nice to get something similar in your repo as well.

**Comment by kornelski** [comment]
That's an interesting result. Thank you for fuzzing it!

I'll check it next week as I'm currently travelling.
