### ISSUE TITLE
Memory leak on decoding a malformed image

### ISSUE THREAD

**Issue by Shnatsel** [kornelski/lodepng-rust#34]
lodepng-rust leaks memory when given malicious input. This issue has been discovered via fuzzing with [afl](https://github.com/rust-fuzz/afl.rs) and [libdiffuzz](https://github.com/Shnatsel/libdiffuzz), later confirmed with [address sanitizer](https://github.com/japaric/rust-san).

Steps to reproduce:

1. Download and unpack [lodepng-repr-diff.tar.gz](https://github.com/kornelski/lodepng-rust/files/2336915/lodepng-repr-diff.tar.gz) - this is a Rust project with Cargo
1. `cd lodepng-repr-diff`
1. `cargo build --release`
1. run `target/release/target/release/lodepng-afl-fuzz-differential < memory_leaking_files/id:000000,sig:06,src:000389,op:havoc,rep:2`  and observe memory consumption of the process steadily increase. This should be the case for any file from memory_leaking_files/

This issue has been discovered in version 2.3.0, so it is distinct from #28

**Comment by kornelski** [comment]
I've tried these files with `valgrind --leak-check=full` and it didn't find any problems.

I believe that is the same issue as #28, fixed in 37a7bccc0a2df94a7ee6eb7cfc1be3192f4d024d

**Comment by Shnatsel** [comment]
Closing as duplicate of #28
