### ISSUE TITLE
Decoding and Re-encoding PNG shifts colors

### ISSUE THREAD

**Issue by jamsinclair** [kornelski/lodepng-rust#52]
## Summary

Firstly, I assume this is either an upstream issue with the original `lodepng` or I am doing something really stupid 😅 

I was trying to decode some MacOS screenshot png files but I am noticing a colour shift in the decoded pixel data.

Is there some flag I need to set or colour channel I need to detect first before decoding (or when encoding)?

| Original PNG | Re-Encoded PNG |
| --- | --- |
| <img width="595" alt="test2" src="https://user-images.githubusercontent.com/5964236/142033084-d5ff00b2-003a-4f78-8551-b31cdf633462.png"> | <img width="595" alt="test2" src="https://user-images.githubusercontent.com/5964236/142033110-53b51925-c59b-48ee-8194-dbf999b3c1f8.png"> |

### Test Code
Mostly taken from your lovely examples 😁 
```rust
let path = &Path::new("write_test.png");

// test.png being the original PNG in https://github.com/kornelski/lodepng-rust/issues/52
match lodepng::decode32_file("test.png") {
    Ok(image) => {
        if let Err(e) = lodepng::encode_file(path, &image.buffer, image.width, image.height, lodepng::ColorType::RGBA, 8) {
            panic!("failed to write png: {:?}", e);
        }

        println!("Written to {}", path.display());
    },
    Err(reason) => println!("Could not load, because: {}", reason),
}
```

**Comment by jamsinclair** [comment]
Ah looks to be an upstream issue https://github.com/lvandeve/lodepng/issues/124. Xcode does some odd things to the images.

Would you consider supporting these quirks or looking to keep parity with the original library? I'm guessing the latter would be best 😊

**Comment by kornelski** [comment]
If it was in the Apple format, it wouldn't decode. 

You probably need to apply color profiles. See https://lib.rs/load_image crate.

**Comment by jamsinclair** [comment]
@kornelski Thanks for your expertise. Seems that Mac screenshots use a `Display` ICC Profile.
