### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by blinxen** [kornelski/lodepng-rust#58]
On GitHub it says that this code is licensed under the "zlib" license, but in `Cargo.toml` the "BSD-3-Clause" license is defined.

Which one is correct?

**Comment by blinxen** [comment]
Also in the COPYRIGHT file, no license is specified. Or am I misunderstanding something? I would like to package this library for fedora, but before I can do that I need to know under which license this library is published.

**Comment by kornelski** [comment]
The `Cargo.toml` specifier is wrong. The license is zlib, because that's the original license of the C lodepng. The copyright file is the zlib license from the original project.

e521e7d9ab88f48b0b76e8b08923de6ac7057ec2

**Comment by HusseinKabbout** [comment]
Thanks for clarifying and fixing!
